POST http://localhost:8080/encode HTTP/1.1
content-type: application/json

{
    "orig": "encode url",
}

###
POST http://localhost:8080/decode HTTP/1.1
content-type: application/json

{
    "short" : "decode url"
}